### ISSUE TITLE
ngProgress plugin is making http calls in Jasmine unit tests

### ISSUE THREAD

**Issue by QuantumInformation** [VictorBjelkholm/ngProgress#31] opened 2014-01-31 14:16 UTC
I have a situation in my unit test where the ngProgress plugin is making http calls, which is messing up my unit tests as I am getting unexpected get errors:

> `Uncaught Error: Unexpected request: GET http://upda...`

here is the stack grace

    > request(), app.js:35 deferred.promise.then.wrappedCallback(),
    > angular.js:10597 deferred.promise.then.wrappedCallback(),
    > angular.js:10597 anonymous(), angular.js:10683 $get.Scope.$eval(),
    > angular.js:11576 $get.Scope.$digest(), angular.js:11421
    > $get.Scope.$apply(), angular.js:11682 updateCount(),
    > ngProgress.min.js:8 anonymous(), ngProgress.min.js:8

**Comment by VictorBjelkholm** [comment] 2015-07-15 20:43
Closing this since I have no idea about how to reproduce. Please comment if you manage to come up with a test case.

**Closed by VictorBjelkholm** 2015-07-15 20:43 UTC
