### ISSUE TITLE
API Color Wrong

### ISSUE THREAD

**Issue by Bernardoow** [VictorBjelkholm/ngProgress#101] opened 2015-12-08 19:01 UTC
ON http://victorbjelkholm.github.io/ngProgress/#api

Change color say : color(), but corret is setColor.

**Comment by cetra3** [comment] 2016-02-09 23:58
Duplicate of https://github.com/VictorBjelkholm/ngProgress/issues/101

**Closed by cetra3** 2016-02-09 23:58 UTC
