### ISSUE TITLE
CSS "color"-properties are not applying

### ISSUE THREAD

**Issue by dasois** [VictorBjelkholm/ngProgress#52] opened 2014-08-27 16:26 UTC
Trying to set the CSS-property "color" in order to change the color of the progressBar does not get applied.

**Comment by cetra3** [comment] 2016-02-15 22:09
Closing this as a duplicate of https://github.com/VictorBjelkholm/ngProgress/issues/33

**Closed by cetra3** 2016-02-15 22:09 UTC
Labels: bug
