### ISSUE TITLE
Case sensitivity issue

### ISSUE THREAD

**Issue by vijayarulmuthu** [VictorBjelkholm/ngProgress#91] opened 2015-09-29 15:39 UTC
In the bower.json file, I find the filenames are camel cased, but the actual file (ngprogress.js) is in lowercase. This inconsistency creates a problem on the LINUX environment.  Could you please fix this asap?

  "main": [
    "build/ngProgress.js",
    "ngProgress.css"
  ],

Thanks!

**Comment by schmod** [comment] 2015-10-29 20:26
Indeed.  This seems to have changed in 1.1.12...

**Comment by Mihail-K** [comment] 2015-11-04 22:23
We've also run into this issue (and it was very tricky to diagnose).

As a temporary workaround, you can add an override to your bower file,

```json
"overrides": {
  "ngprogress": {
    "main": [
      "build/ngprogress.js",
      "ngProgress.css"
    ]
  }
}
```

Note that you will have to remove it if the issue is resolved in a future version.

**Comment by ttgraham** [comment] 2015-11-20 19:29
Thank you @Mihail-K for the override. +1 to fixing this, spent my morning tracking down a gulp inconsistency in a new environment.

**Comment by cetra3** [comment] 2016-02-09 23:43
Fixed by https://github.com/VictorBjelkholm/ngProgress/pull/77

**Closed by cetra3** 2016-02-09 23:43 UTC
